// This file is auto-generated by @hey-api/openapi-ts

import {type Client, type Options as ClientOptions, type TDataShape, urlSearchParamsBodySerializer} from './client';
import type {
    AuthorizeApiOauthAuthPostData,
    AuthorizeApiOauthAuthPostErrors,
    AuthorizeApiOauthAuthPostResponses,
    AuthorizeDeviceApiOauthDevicecodePostData,
    AuthorizeDeviceApiOauthDevicecodePostErrors,
    AuthorizeDeviceApiOauthDevicecodePostResponses,
    AuthorizeJsonApiOauthAuthJsonPostData,
    AuthorizeJsonApiOauthAuthJsonPostErrors,
    AuthorizeJsonApiOauthAuthJsonPostResponses,
    DevicesCreateData,
    DevicesCreateErrors,
    DevicesCreateResponses,
    DevicesDeleteData,
    DevicesDeleteErrors,
    DevicesDeleteResponses,
    DevicesGetData,
    DevicesGetErrors,
    DevicesGetResponses,
    DevicesListData,
    DevicesListErrors,
    DevicesListResponses,
    DevicesUpdateData,
    DevicesUpdateErrors,
    DevicesUpdateResponses,
    HealthCheckHealthGetData,
    HealthCheckHealthGetResponses,
    LoginForAccessTokenApiAuthTokenPostData,
    LoginForAccessTokenApiAuthTokenPostErrors,
    LoginForAccessTokenApiAuthTokenPostResponses,
    LoginForAccessTokenApiOauthTokenPostData,
    LoginForAccessTokenApiOauthTokenPostErrors,
    LoginForAccessTokenApiOauthTokenPostResponses,
    RegisterUserApiAuthRegisterPostData,
    RegisterUserApiAuthRegisterPostErrors,
    RegisterUserApiAuthRegisterPostResponses,
    RootGetData,
    RootGetResponses,
    RoutinesCreateData,
    RoutinesCreateErrors,
    RoutinesCreateResponses,
    RoutinesDeleteData,
    RoutinesDeleteErrors,
    RoutinesDeleteResponses,
    RoutinesEndData,
    RoutinesEndErrors,
    RoutinesEndResponses,
    RoutinesGetData,
    RoutinesGetErrors,
    RoutinesGetResponses,
    RoutinesListData,
    RoutinesListErrors,
    RoutinesListResponses,
    RoutinesStartData,
    RoutinesStartErrors,
    RoutinesStartResponses,
    RoutinesTasksAddData,
    RoutinesTasksAddErrors,
    RoutinesTasksAddResponses,
    RoutinesTasksListData,
    RoutinesTasksListErrors,
    RoutinesTasksListResponses,
    RoutinesTasksRemoveData,
    RoutinesTasksRemoveErrors,
    RoutinesTasksRemoveResponses,
    RoutinesUpdateData,
    RoutinesUpdateErrors,
    RoutinesUpdateResponses,
    TasksCreateData,
    TasksCreateErrors,
    TasksCreateResponses,
    TasksDeleteData,
    TasksDeleteErrors,
    TasksDeleteResponses,
    TasksListData,
    TasksListResponses,
    TasksUpdateData,
    TasksUpdateErrors,
    TasksUpdateResponses,
    UsersMeData,
    UsersMeErrors,
    UsersMeResponses,
    VerifyDeviceCodeApiOauthDeviceVerifyPostData,
    VerifyDeviceCodeApiOauthDeviceVerifyPostErrors,
    VerifyDeviceCodeApiOauthDeviceVerifyPostResponses
} from './types.gen';
import {client} from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Login For Access Token
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static loginForAccessTokenApiAuthTokenPost<ThrowOnError extends boolean = false>(options: Options<LoginForAccessTokenApiAuthTokenPostData, ThrowOnError>) {
        return (options.client ?? client).post<LoginForAccessTokenApiAuthTokenPostResponses, LoginForAccessTokenApiAuthTokenPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/auth/token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Register User
     * Register a new user
     */
    public static registerUserApiAuthRegisterPost<ThrowOnError extends boolean = false>(options?: Options<RegisterUserApiAuthRegisterPostData, ThrowOnError>) {
        return (options?.client ?? client).post<RegisterUserApiAuthRegisterPostResponses, RegisterUserApiAuthRegisterPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/register',
            ...options
        });
    }
    
    /**
     * Login For Access Token
     * OAuth2 Token Endpoint
     * - Supports Password Grant (username/password)
     * - Supports Authorization Code Grant with PKCE (Alexa/public client)
     * - Supports Device Code Grant
     * - Supports Refresh Token Grant
     */
    public static loginForAccessTokenApiOauthTokenPost<ThrowOnError extends boolean = false>(options?: Options<LoginForAccessTokenApiOauthTokenPostData, ThrowOnError>) {
        return (options?.client ?? client).post<LoginForAccessTokenApiOauthTokenPostResponses, LoginForAccessTokenApiOauthTokenPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/oauth/token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Authorize Device
     */
    public static authorizeDeviceApiOauthDevicecodePost<ThrowOnError extends boolean = false>(options?: Options<AuthorizeDeviceApiOauthDevicecodePostData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthorizeDeviceApiOauthDevicecodePostResponses, AuthorizeDeviceApiOauthDevicecodePostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/oauth/devicecode',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Authorize
     */
    public static authorizeApiOauthAuthPost<ThrowOnError extends boolean = false>(options?: Options<AuthorizeApiOauthAuthPostData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthorizeApiOauthAuthPostResponses, AuthorizeApiOauthAuthPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/oauth/auth',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Authorizejson
     */
    public static authorizeJsonApiOauthAuthJsonPost<ThrowOnError extends boolean = false>(options?: Options<AuthorizeJsonApiOauthAuthJsonPostData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthorizeJsonApiOauthAuthJsonPostResponses, AuthorizeJsonApiOauthAuthJsonPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/oauth/auth-json',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Verify Device Code
     * Verify a device by entering the `user_code` on the verification page.
     * Uses application/x-www-form-urlencoded form data.
     */
    public static verifyDeviceCodeApiOauthDeviceVerifyPost<ThrowOnError extends boolean = false>(options?: Options<VerifyDeviceCodeApiOauthDeviceVerifyPostData, ThrowOnError>) {
        return (options?.client ?? client).post<VerifyDeviceCodeApiOauthDeviceVerifyPostResponses, VerifyDeviceCodeApiOauthDeviceVerifyPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/oauth/device/verify',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
}

export class Devices {
    /**
     * Get Devices
     * Get all devices for the current user
     */
    public static devicesList<ThrowOnError extends boolean = false>(options?: Options<DevicesListData, ThrowOnError>) {
        return (options?.client ?? client).get<DevicesListResponses, DevicesListErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/devices/',
            ...options
        });
    }
    
    /**
     * Create Device
     * Create a new device
     */
    public static devicesCreate<ThrowOnError extends boolean = false>(options: Options<DevicesCreateData, ThrowOnError>) {
        return (options.client ?? client).post<DevicesCreateResponses, DevicesCreateErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/devices/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Device
     * Delete a device
     */
    public static devicesDelete<ThrowOnError extends boolean = false>(options: Options<DevicesDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<DevicesDeleteResponses, DevicesDeleteErrors, ThrowOnError>({
            url: '/api/devices/{device_id}',
            ...options
        });
    }
    
    /**
     * Get Device
     * Get a specific device by ID
     */
    public static devicesGet<ThrowOnError extends boolean = false>(options: Options<DevicesGetData, ThrowOnError>) {
        return (options.client ?? client).get<DevicesGetResponses, DevicesGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/devices/{device_id}',
            ...options
        });
    }
    
    /**
     * Update Device
     * Update a device
     */
    public static devicesUpdate<ThrowOnError extends boolean = false>(options: Options<DevicesUpdateData, ThrowOnError>) {
        return (options.client ?? client).put<DevicesUpdateResponses, DevicesUpdateErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/devices/{device_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Users {
    /**
     * Get Current User
     * Get current user information
     */
    public static usersMe<ThrowOnError extends boolean = false>(options?: Options<UsersMeData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersMeResponses, UsersMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/me',
            ...options
        });
    }

    /**
     * Change Password
     * Change current user's password
     */
    public static usersChangePassword<ThrowOnError extends boolean = false>(options: Options<UsersChangePasswordData, ThrowOnError>) {
        return (options.client ?? client).post<UsersChangePasswordResponses, UsersChangePasswordErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/change-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Tasks {
    /**
     * List My Tasks
     * List all tasks owned by the current user.
     */
    public static tasksList<ThrowOnError extends boolean = false>(options?: Options<TasksListData, ThrowOnError>) {
        return (options?.client ?? client).get<TasksListResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options
        });
    }
    
    /**
     * Create Task
     * Create a new task owned by the current user. Returns the created task.
     */
    public static tasksCreate<ThrowOnError extends boolean = false>(options: Options<TasksCreateData, ThrowOnError>) {
        return (options.client ?? client).post<TasksCreateResponses, TasksCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Task
     * Delete a task only if you are its owner and it is not used in routines owned by other users.
     */
    public static tasksDelete<ThrowOnError extends boolean = false>(options: Options<TasksDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<TasksDeleteResponses, TasksDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options
        });
    }
    
    /**
     * Update Task
     * Update mutable fields of a task. All fields are optional; only provided fields are updated.
     */
    public static tasksUpdate<ThrowOnError extends boolean = false>(options: Options<TasksUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<TasksUpdateResponses, TasksUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Routines {
    /**
     * List Routines
     */
    public static routinesList<ThrowOnError extends boolean = false>(options?: Options<RoutinesListData, ThrowOnError>) {
        return (options?.client ?? client).get<RoutinesListResponses, RoutinesListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options
        });
    }
    
    /**
     * Create Routine
     */
    public static routinesCreate<ThrowOnError extends boolean = false>(options: Options<RoutinesCreateData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesCreateResponses, RoutinesCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Routine
     */
    public static routinesDelete<ThrowOnError extends boolean = false>(options: Options<RoutinesDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesDeleteResponses, RoutinesDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Get Routine
     */
    public static routinesGet<ThrowOnError extends boolean = false>(options: Options<RoutinesGetData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesGetResponses, RoutinesGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Update Routine
     */
    public static routinesUpdate<ThrowOnError extends boolean = false>(options: Options<RoutinesUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<RoutinesUpdateResponses, RoutinesUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Routine Tasks
     */
    public static routinesTasksList<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksListData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesTasksListResponses, RoutinesTasksListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options
        });
    }
    
    /**
     * Add Task To Routine
     */
    public static routinesTasksAdd<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksAddData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesTasksAddResponses, RoutinesTasksAddErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove Task From Routine
     */
    public static routinesTasksRemove<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksRemoveData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesTasksRemoveResponses, RoutinesTasksRemoveErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks/{position}',
            ...options
        });
    }
    
    /**
     * Start Routine
     */
    public static routinesStart<ThrowOnError extends boolean = false>(options: Options<RoutinesStartData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesStartResponses, RoutinesStartErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/start',
            ...options
        });
    }
    
    /**
     * End Routine
     */
    public static routinesEnd<ThrowOnError extends boolean = false>(options: Options<RoutinesEndData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesEndResponses, RoutinesEndErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/end',
            ...options
        });
    }
}

export class Default {
    /**
     * Root
     */
    public static rootGet<ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) {
        return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/',
            ...options
        });
    }
    
    /**
     * Health Check
     */
    public static healthCheckHealthGet<ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) {
        return (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/health',
            ...options
        });
    }
}
