// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { DevicesListData, DevicesListResponses, DevicesListErrors, DevicesGetData, DevicesGetResponses, DevicesGetErrors, UsersMeData, UsersMeResponses, UsersMeErrors, UsersListData, UsersListResponses, UsersListErrors, TasksListData, TasksListResponses, TasksListErrors, TasksCreateData, TasksCreateResponses, TasksCreateErrors, TasksDeleteData, TasksDeleteResponses, TasksDeleteErrors, TasksUpdateData, TasksUpdateResponses, TasksUpdateErrors, RoutinesListData, RoutinesListResponses, RoutinesListErrors, RoutinesCreateData, RoutinesCreateResponses, RoutinesCreateErrors, RoutinesActiveStatusData, RoutinesActiveStatusResponses, RoutinesActiveStatusErrors, RoutinesActiveSkipData, RoutinesActiveSkipResponses, RoutinesActiveSkipErrors, RoutinesActivePauseData, RoutinesActivePauseResponses, RoutinesActivePauseErrors, RoutinesActiveResumeData, RoutinesActiveResumeResponses, RoutinesActiveResumeErrors, RoutinesDeleteData, RoutinesDeleteResponses, RoutinesDeleteErrors, RoutinesGetData, RoutinesGetResponses, RoutinesGetErrors, RoutinesUpdateData, RoutinesUpdateResponses, RoutinesUpdateErrors, RoutinesTasksListData, RoutinesTasksListResponses, RoutinesTasksListErrors, RoutinesTasksAddData, RoutinesTasksAddResponses, RoutinesTasksAddErrors, RoutinesTasksRemoveData, RoutinesTasksRemoveResponses, RoutinesTasksRemoveErrors, RoutinesStartData, RoutinesStartResponses, RoutinesStartErrors, StartRoutineByNameApiRoutineControlStartPostData, StartRoutineByNameApiRoutineControlStartPostResponses, StartRoutineByNameApiRoutineControlStartPostErrors, StopCurrentRoutineApiRoutineControlStopPostData, StopCurrentRoutineApiRoutineControlStopPostResponses, StopCurrentRoutineApiRoutineControlStopPostErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Devices {
    /**
     * List Devices
     * Return all devices that belong to the authenticated user.
     */
    public static devicesList<ThrowOnError extends boolean = false>(options?: Options<DevicesListData, ThrowOnError>) {
        return (options?.client ?? client).get<DevicesListResponses, DevicesListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/devices/',
            ...options
        });
    }
    
    /**
     * Get Device
     * Return a single device by ID if it belongs to the authenticated user.
     */
    public static devicesGet<ThrowOnError extends boolean = false>(options: Options<DevicesGetData, ThrowOnError>) {
        return (options.client ?? client).get<DevicesGetResponses, DevicesGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/devices/{device_id}',
            ...options
        });
    }
}

export class Users {
    /**
     * Get Current User Me
     * Get current user information and sync with OIDC
     */
    public static usersMe<ThrowOnError extends boolean = false>(options?: Options<UsersMeData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersMeResponses, UsersMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/me',
            ...options
        });
    }
    
    /**
     * List Users
     * List all users.
     */
    public static usersList<ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersListResponses, UsersListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/',
            ...options
        });
    }
}

export class Tasks {
    /**
     * List My Tasks
     * List all tasks owned by the current user.
     */
    public static tasksList<ThrowOnError extends boolean = false>(options?: Options<TasksListData, ThrowOnError>) {
        return (options?.client ?? client).get<TasksListResponses, TasksListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options
        });
    }
    
    /**
     * Create Task
     * Create a new task owned by the current user. Returns the created task.
     */
    public static tasksCreate<ThrowOnError extends boolean = false>(options: Options<TasksCreateData, ThrowOnError>) {
        return (options.client ?? client).post<TasksCreateResponses, TasksCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Task
     * Delete a task only if you are its owner and it is not used in routines owned by other users.
     */
    public static tasksDelete<ThrowOnError extends boolean = false>(options: Options<TasksDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<TasksDeleteResponses, TasksDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options
        });
    }
    
    /**
     * Update Task
     * Update mutable fields of a task. All fields are optional; only provided fields are updated.
     */
    public static tasksUpdate<ThrowOnError extends boolean = false>(options: Options<TasksUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<TasksUpdateResponses, TasksUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Routines {
    /**
     * List Routines
     */
    public static routinesList<ThrowOnError extends boolean = false>(options?: Options<RoutinesListData, ThrowOnError>) {
        return (options?.client ?? client).get<RoutinesListResponses, RoutinesListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options
        });
    }
    
    /**
     * Create Routine
     */
    public static routinesCreate<ThrowOnError extends boolean = false>(options: Options<RoutinesCreateData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesCreateResponses, RoutinesCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Active Status
     */
    public static routinesActiveStatus<ThrowOnError extends boolean = false>(options?: Options<RoutinesActiveStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<RoutinesActiveStatusResponses, RoutinesActiveStatusErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/active/status',
            ...options
        });
    }
    
    /**
     * Skip Active Task
     */
    public static routinesActiveSkip<ThrowOnError extends boolean = false>(options?: Options<RoutinesActiveSkipData, ThrowOnError>) {
        return (options?.client ?? client).post<RoutinesActiveSkipResponses, RoutinesActiveSkipErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/active/skip',
            ...options
        });
    }
    
    /**
     * Pause Active Routine
     */
    public static routinesActivePause<ThrowOnError extends boolean = false>(options?: Options<RoutinesActivePauseData, ThrowOnError>) {
        return (options?.client ?? client).post<RoutinesActivePauseResponses, RoutinesActivePauseErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/active/pause',
            ...options
        });
    }
    
    /**
     * Resume Active Routine
     */
    public static routinesActiveResume<ThrowOnError extends boolean = false>(options?: Options<RoutinesActiveResumeData, ThrowOnError>) {
        return (options?.client ?? client).post<RoutinesActiveResumeResponses, RoutinesActiveResumeErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/active/resume',
            ...options
        });
    }
    
    /**
     * Delete Routine
     */
    public static routinesDelete<ThrowOnError extends boolean = false>(options: Options<RoutinesDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesDeleteResponses, RoutinesDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Get Routine
     */
    public static routinesGet<ThrowOnError extends boolean = false>(options: Options<RoutinesGetData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesGetResponses, RoutinesGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Update Routine
     */
    public static routinesUpdate<ThrowOnError extends boolean = false>(options: Options<RoutinesUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<RoutinesUpdateResponses, RoutinesUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Routine Tasks
     */
    public static routinesTasksList<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksListData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesTasksListResponses, RoutinesTasksListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options
        });
    }
    
    /**
     * Add Task To Routine
     */
    public static routinesTasksAdd<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksAddData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesTasksAddResponses, RoutinesTasksAddErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove Task From Routine
     */
    public static routinesTasksRemove<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksRemoveData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesTasksRemoveResponses, RoutinesTasksRemoveErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks/{position}',
            ...options
        });
    }
    
    /**
     * Start Routine
     */
    public static routinesStart<ThrowOnError extends boolean = false>(options: Options<RoutinesStartData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesStartResponses, RoutinesStartErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/start',
            ...options
        });
    }
}

export class RoutineControl {
    /**
     * Start Routine By Name
     */
    public static startRoutineByNameApiRoutineControlStartPost<ThrowOnError extends boolean = false>(options: Options<StartRoutineByNameApiRoutineControlStartPostData, ThrowOnError>) {
        return (options.client ?? client).post<StartRoutineByNameApiRoutineControlStartPostResponses, StartRoutineByNameApiRoutineControlStartPostErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routine-control/start',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Stop Current Routine
     */
    public static stopCurrentRoutineApiRoutineControlStopPost<ThrowOnError extends boolean = false>(options?: Options<StopCurrentRoutineApiRoutineControlStopPostData, ThrowOnError>) {
        return (options?.client ?? client).post<StopCurrentRoutineApiRoutineControlStopPostResponses, StopCurrentRoutineApiRoutineControlStopPostErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routine-control/stop',
            ...options
        });
    }
}
