// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type Client, type TDataShape, urlSearchParamsBodySerializer } from './client';
import type { DevicesListData, DevicesListResponses, DevicesListErrors, DevicesGetData, DevicesGetResponses, DevicesGetErrors, UsersMeData, UsersMeResponses, UsersMeErrors, UsersChangePasswordData, UsersChangePasswordResponses, UsersChangePasswordErrors, UsersListData, UsersListResponses, UsersListErrors, UsersCreateData, UsersCreateResponses, UsersCreateErrors, OauthTokenData, OauthTokenResponses, OauthTokenErrors, OauthAuthorizeData, OauthAuthorizeResponses, OauthAuthorizeErrors, OauthConsentData, OauthConsentResponses, OauthConsentErrors, OauthDeviceAuthorizationData, OauthDeviceAuthorizationResponses, OauthDeviceAuthorizationErrors, OauthDeviceVerifyData, OauthDeviceVerifyResponses, OauthDeviceVerifyErrors, TasksListData, TasksListResponses, TasksCreateData, TasksCreateResponses, TasksCreateErrors, TasksDeleteData, TasksDeleteResponses, TasksDeleteErrors, TasksUpdateData, TasksUpdateResponses, TasksUpdateErrors, RoutinesListData, RoutinesListResponses, RoutinesListErrors, RoutinesCreateData, RoutinesCreateResponses, RoutinesCreateErrors, RoutinesDeleteData, RoutinesDeleteResponses, RoutinesDeleteErrors, RoutinesGetData, RoutinesGetResponses, RoutinesGetErrors, RoutinesUpdateData, RoutinesUpdateResponses, RoutinesUpdateErrors, RoutinesTasksListData, RoutinesTasksListResponses, RoutinesTasksListErrors, RoutinesTasksAddData, RoutinesTasksAddResponses, RoutinesTasksAddErrors, RoutinesTasksRemoveData, RoutinesTasksRemoveResponses, RoutinesTasksRemoveErrors, RoutinesStartData, RoutinesStartResponses, RoutinesStartErrors, RoutinesEndData, RoutinesEndResponses, RoutinesEndErrors, RootGetData, RootGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Devices {
    /**
     * List Devices
     * Return all devices that belong to the authenticated user.
     */
    public static devicesList<ThrowOnError extends boolean = false>(options?: Options<DevicesListData, ThrowOnError>) {
        return (options?.client ?? client).get<DevicesListResponses, DevicesListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/devices/',
            ...options
        });
    }
    
    /**
     * Get Device
     * Return a single device by ID if it belongs to the authenticated user.
     */
    public static devicesGet<ThrowOnError extends boolean = false>(options: Options<DevicesGetData, ThrowOnError>) {
        return (options.client ?? client).get<DevicesGetResponses, DevicesGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/devices/{device_id}',
            ...options
        });
    }
}

export class Users {
    /**
     * Get Current User Me
     * Get current user information
     */
    public static usersMe<ThrowOnError extends boolean = false>(options?: Options<UsersMeData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersMeResponses, UsersMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/me',
            ...options
        });
    }
    
    /**
     * Change Password
     * Change current user's password
     */
    public static usersChangePassword<ThrowOnError extends boolean = false>(options: Options<UsersChangePasswordData, ThrowOnError>) {
        return (options.client ?? client).post<UsersChangePasswordResponses, UsersChangePasswordErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/change-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Users
     * List all users.
     */
    public static usersList<ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersListResponses, UsersListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/',
            ...options
        });
    }
    
    /**
     * Create User
     * Create new user.
     */
    public static usersCreate<ThrowOnError extends boolean = false>(options: Options<UsersCreateData, ThrowOnError>) {
        return (options.client ?? client).post<UsersCreateResponses, UsersCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Oauth2 {
    /**
     * Token
     */
    public static oauthToken<ThrowOnError extends boolean = false>(options?: Options<OauthTokenData, ThrowOnError>) {
        return (options?.client ?? client).post<OauthTokenResponses, OauthTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/oauth/token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Authorize
     */
    public static oauthAuthorize<ThrowOnError extends boolean = false>(options?: Options<OauthAuthorizeData, ThrowOnError>) {
        return (options?.client ?? client).get<OauthAuthorizeResponses, OauthAuthorizeErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/oauth/authorize',
            ...options
        });
    }
    
    /**
     * Oauth Consent
     */
    public static oauthConsent<ThrowOnError extends boolean = false>(options?: Options<OauthConsentData, ThrowOnError>) {
        return (options?.client ?? client).post<OauthConsentResponses, OauthConsentErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/oauth/consent',
            ...options
        });
    }
    
    /**
     * Device Authorization
     */
    public static oauthDeviceAuthorization<ThrowOnError extends boolean = false>(options?: Options<OauthDeviceAuthorizationData, ThrowOnError>) {
        return (options?.client ?? client).post<OauthDeviceAuthorizationResponses, OauthDeviceAuthorizationErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/oauth/device_authorization',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Device Verify
     */
    public static oauthDeviceVerify<ThrowOnError extends boolean = false>(options?: Options<OauthDeviceVerifyData, ThrowOnError>) {
        return (options?.client ?? client).post<OauthDeviceVerifyResponses, OauthDeviceVerifyErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/oauth/device/verify',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
}

export class Tasks {
    /**
     * List My Tasks
     * List all tasks owned by the current user.
     */
    public static tasksList<ThrowOnError extends boolean = false>(options?: Options<TasksListData, ThrowOnError>) {
        return (options?.client ?? client).get<TasksListResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options
        });
    }
    
    /**
     * Create Task
     * Create a new task owned by the current user. Returns the created task.
     */
    public static tasksCreate<ThrowOnError extends boolean = false>(options: Options<TasksCreateData, ThrowOnError>) {
        return (options.client ?? client).post<TasksCreateResponses, TasksCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Task
     * Delete a task only if you are its owner and it is not used in routines owned by other users.
     */
    public static tasksDelete<ThrowOnError extends boolean = false>(options: Options<TasksDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<TasksDeleteResponses, TasksDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options
        });
    }
    
    /**
     * Update Task
     * Update mutable fields of a task. All fields are optional; only provided fields are updated.
     */
    public static tasksUpdate<ThrowOnError extends boolean = false>(options: Options<TasksUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<TasksUpdateResponses, TasksUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/tasks/{task_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Routines {
    /**
     * List Routines
     */
    public static routinesList<ThrowOnError extends boolean = false>(options?: Options<RoutinesListData, ThrowOnError>) {
        return (options?.client ?? client).get<RoutinesListResponses, RoutinesListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options
        });
    }
    
    /**
     * Create Routine
     */
    public static routinesCreate<ThrowOnError extends boolean = false>(options: Options<RoutinesCreateData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesCreateResponses, RoutinesCreateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Routine
     */
    public static routinesDelete<ThrowOnError extends boolean = false>(options: Options<RoutinesDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesDeleteResponses, RoutinesDeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Get Routine
     */
    public static routinesGet<ThrowOnError extends boolean = false>(options: Options<RoutinesGetData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesGetResponses, RoutinesGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options
        });
    }
    
    /**
     * Update Routine
     */
    public static routinesUpdate<ThrowOnError extends boolean = false>(options: Options<RoutinesUpdateData, ThrowOnError>) {
        return (options.client ?? client).patch<RoutinesUpdateResponses, RoutinesUpdateErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Routine Tasks
     */
    public static routinesTasksList<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksListData, ThrowOnError>) {
        return (options.client ?? client).get<RoutinesTasksListResponses, RoutinesTasksListErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options
        });
    }
    
    /**
     * Add Task To Routine
     */
    public static routinesTasksAdd<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksAddData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesTasksAddResponses, RoutinesTasksAddErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove Task From Routine
     */
    public static routinesTasksRemove<ThrowOnError extends boolean = false>(options: Options<RoutinesTasksRemoveData, ThrowOnError>) {
        return (options.client ?? client).delete<RoutinesTasksRemoveResponses, RoutinesTasksRemoveErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/tasks/{position}',
            ...options
        });
    }
    
    /**
     * Start Routine
     */
    public static routinesStart<ThrowOnError extends boolean = false>(options: Options<RoutinesStartData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesStartResponses, RoutinesStartErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/start',
            ...options
        });
    }
    
    /**
     * End Routine
     */
    public static routinesEnd<ThrowOnError extends boolean = false>(options: Options<RoutinesEndData, ThrowOnError>) {
        return (options.client ?? client).post<RoutinesEndResponses, RoutinesEndErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/routines/{routine_id}/end',
            ...options
        });
    }
}

export class Default {
    /**
     * Root
     */
    public static rootGet<ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) {
        return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/',
            ...options
        });
    }
    
    /**
     * Health Check
     */
    public static healthCheckHealthGet<ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) {
        return (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/health',
            ...options
        });
    }
}
