// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccessLevel
 */
export type AccessLevel = 'owner' | 'write' | 'read';

/**
 * ActiveRoutineStatusRead
 */
export type ActiveRoutineStatusRead = {
    /**
     * Active Routine Id
     */
    active_routine_id?: number | null;
    /**
     * Routine Name
     */
    routine_name?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Current Task Position
     */
    current_task_position?: number | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Paused At
     */
    paused_at?: string | null;
    /**
     * Pause Duration
     */
    pause_duration?: number;
};

/**
 * Device
 */
export type DeviceRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    status?: DeviceStatus;
};

/**
 * DeviceStatus
 */
export type DeviceStatus = 'online' | 'offline';

/**
 * FriendAdd
 */
export type FriendAdd = {
    /**
     * Friend Code
     */
    friend_code: string;
};

/**
 * FriendRead
 */
export type FriendRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    status?: FriendshipStatus;
};

/**
 * FriendshipStatus
 */
export type FriendshipStatus = 'pending' | 'accepted';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RoutineCreate
 */
export type RoutineCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Routine
 */
export type RoutineRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    access_level?: AccessLevel;
    /**
     * Tasks
     */
    tasks?: Array<TaskInRoutineRead> | null;
};

/**
 * RoutineStartPayload
 */
export type RoutineStartPayload = {
    /**
     * Name
     */
    name: string;
};

/**
 * RoutineTaskAdd
 */
export type RoutineTaskAdd = {
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * RoutineUpdate
 */
export type RoutineUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
};

/**
 * TaskInRoutineRead
 */
export type TaskInRoutineRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Position
     */
    position: number;
};

/**
 * Task
 */
export type TaskRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Id
     */
    id: number;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Icon Name
     */
    icon_name?: string | null;
    /**
     * Sound
     */
    sound?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
};

/**
 * UserRead
 * Schema for returning user data.
 */
export type UserRead = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Oidc Sub
     */
    oidc_sub: string;
    /**
     * Friend Code
     */
    friend_code?: string | null;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    /**
     * Id
     */
    id: number;
};

/**
 * UserUpdate
 * Schema for updating a user.
 */
export type UserUpdate = {
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DevicesListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/devices/';
};

export type DevicesListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DevicesListError = DevicesListErrors[keyof DevicesListErrors];

export type DevicesListResponses = {
    /**
     * Response Devices List
     * Successful Response
     */
    200: Array<DeviceRead>;
};

export type DevicesListResponse = DevicesListResponses[keyof DevicesListResponses];

export type DevicesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Device Id
         */
        device_id: number;
    };
    query?: never;
    url: '/api/devices/{device_id}';
};

export type DevicesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DevicesGetError = DevicesGetErrors[keyof DevicesGetErrors];

export type DevicesGetResponses = {
    /**
     * Successful Response
     */
    200: DeviceRead;
};

export type DevicesGetResponse = DevicesGetResponses[keyof DevicesGetResponses];

export type UsersMeData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersMeErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersMeError = UsersMeErrors[keyof UsersMeErrors];

export type UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersMeResponse = UsersMeResponses[keyof UsersMeResponses];

export type UsersUpdateMeData = {
    body: UserUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersUpdateMeErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateMeError = UsersUpdateMeErrors[keyof UsersUpdateMeErrors];

export type UsersUpdateMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUpdateMeResponse = UsersUpdateMeResponses[keyof UsersUpdateMeResponses];

export type UsersListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersListError = UsersListErrors[keyof UsersListErrors];

export type UsersListResponses = {
    /**
     * Response Users List
     * Successful Response
     */
    200: Array<UserRead>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type TasksListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksListError = TasksListErrors[keyof TasksListErrors];

export type TasksListResponses = {
    /**
     * Response Tasks List
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type TasksListResponse = TasksListResponses[keyof TasksListResponses];

export type TasksCreateData = {
    body: TaskCreate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksCreateError = TasksCreateErrors[keyof TasksCreateErrors];

export type TasksCreateResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type TasksCreateResponse = TasksCreateResponses[keyof TasksCreateResponses];

export type TasksDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksDeleteError = TasksDeleteErrors[keyof TasksDeleteErrors];

export type TasksDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TasksDeleteResponse = TasksDeleteResponses[keyof TasksDeleteResponses];

export type TasksUpdateData = {
    body: TaskUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksUpdateError = TasksUpdateErrors[keyof TasksUpdateErrors];

export type TasksUpdateResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type TasksUpdateResponse = TasksUpdateResponses[keyof TasksUpdateResponses];

export type RoutinesListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Tasks
         * Include tasks for each routine
         */
        include_tasks?: boolean;
    };
    url: '/api/routines/';
};

export type RoutinesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesListError = RoutinesListErrors[keyof RoutinesListErrors];

export type RoutinesListResponses = {
    /**
     * Response Routines List
     * Successful Response
     */
    200: Array<RoutineRead>;
};

export type RoutinesListResponse = RoutinesListResponses[keyof RoutinesListResponses];

export type RoutinesCreateData = {
    body: RoutineCreate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/';
};

export type RoutinesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesCreateError = RoutinesCreateErrors[keyof RoutinesCreateErrors];

export type RoutinesCreateResponses = {
    /**
     * Successful Response
     */
    201: RoutineRead;
};

export type RoutinesCreateResponse = RoutinesCreateResponses[keyof RoutinesCreateResponses];

export type RoutinesActiveStatusData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/active/status';
};

export type RoutinesActiveStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesActiveStatusError = RoutinesActiveStatusErrors[keyof RoutinesActiveStatusErrors];

export type RoutinesActiveStatusResponses = {
    /**
     * Successful Response
     */
    200: ActiveRoutineStatusRead;
};

export type RoutinesActiveStatusResponse = RoutinesActiveStatusResponses[keyof RoutinesActiveStatusResponses];

export type RoutinesActiveSkipData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/active/skip';
};

export type RoutinesActiveSkipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesActiveSkipError = RoutinesActiveSkipErrors[keyof RoutinesActiveSkipErrors];

export type RoutinesActiveSkipResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type RoutinesActivePauseData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/active/pause';
};

export type RoutinesActivePauseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesActivePauseError = RoutinesActivePauseErrors[keyof RoutinesActivePauseErrors];

export type RoutinesActivePauseResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type RoutinesActiveResumeData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/active/resume';
};

export type RoutinesActiveResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesActiveResumeError = RoutinesActiveResumeErrors[keyof RoutinesActiveResumeErrors];

export type RoutinesActiveResumeResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type RoutinesDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesDeleteError = RoutinesDeleteErrors[keyof RoutinesDeleteErrors];

export type RoutinesDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RoutinesDeleteResponse = RoutinesDeleteResponses[keyof RoutinesDeleteResponses];

export type RoutinesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesGetError = RoutinesGetErrors[keyof RoutinesGetErrors];

export type RoutinesGetResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesGetResponse = RoutinesGetResponses[keyof RoutinesGetResponses];

export type RoutinesUpdateData = {
    body: RoutineUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesUpdateError = RoutinesUpdateErrors[keyof RoutinesUpdateErrors];

export type RoutinesUpdateResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesUpdateResponse = RoutinesUpdateResponses[keyof RoutinesUpdateResponses];

export type RoutinesTasksListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksListError = RoutinesTasksListErrors[keyof RoutinesTasksListErrors];

export type RoutinesTasksListResponses = {
    /**
     * Response Routines Tasks List
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksListResponse = RoutinesTasksListResponses[keyof RoutinesTasksListResponses];

export type RoutinesTasksAddData = {
    body: RoutineTaskAdd;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksAddErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksAddError = RoutinesTasksAddErrors[keyof RoutinesTasksAddErrors];

export type RoutinesTasksAddResponses = {
    /**
     * Response Routines Tasks Add
     * Successful Response
     */
    201: Array<TaskInRoutineRead>;
};

export type RoutinesTasksAddResponse = RoutinesTasksAddResponses[keyof RoutinesTasksAddResponses];

export type RoutinesTasksRemoveData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * Position
         */
        position: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks/{position}';
};

export type RoutinesTasksRemoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksRemoveError = RoutinesTasksRemoveErrors[keyof RoutinesTasksRemoveErrors];

export type RoutinesTasksRemoveResponses = {
    /**
     * Response Routines Tasks Remove
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksRemoveResponse = RoutinesTasksRemoveResponses[keyof RoutinesTasksRemoveResponses];

export type RoutinesStartData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/start';
};

export type RoutinesStartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesStartError = RoutinesStartErrors[keyof RoutinesStartErrors];

export type RoutinesStartResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type StartRoutineByNameApiRoutineControlStartPostData = {
    body: RoutineStartPayload;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routine-control/start';
};

export type StartRoutineByNameApiRoutineControlStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartRoutineByNameApiRoutineControlStartPostError = StartRoutineByNameApiRoutineControlStartPostErrors[keyof StartRoutineByNameApiRoutineControlStartPostErrors];

export type StartRoutineByNameApiRoutineControlStartPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type StopCurrentRoutineApiRoutineControlStopPostData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routine-control/stop';
};

export type StopCurrentRoutineApiRoutineControlStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopCurrentRoutineApiRoutineControlStopPostError = StopCurrentRoutineApiRoutineControlStopPostErrors[keyof StopCurrentRoutineApiRoutineControlStopPostErrors];

export type StopCurrentRoutineApiRoutineControlStopPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type FriendsListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/';
};

export type FriendsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsListError = FriendsListErrors[keyof FriendsListErrors];

export type FriendsListResponses = {
    /**
     * Response Friends List
     * Successful Response
     */
    200: Array<FriendRead>;
};

export type FriendsListResponse = FriendsListResponses[keyof FriendsListResponses];

export type FriendsRequestsListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/requests';
};

export type FriendsRequestsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsRequestsListError = FriendsRequestsListErrors[keyof FriendsRequestsListErrors];

export type FriendsRequestsListResponses = {
    /**
     * Response Friends Requests List
     * Successful Response
     */
    200: Array<FriendRead>;
};

export type FriendsRequestsListResponse = FriendsRequestsListResponses[keyof FriendsRequestsListResponses];

export type FriendsAddData = {
    body: FriendAdd;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/add';
};

export type FriendsAddErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsAddError = FriendsAddErrors[keyof FriendsAddErrors];

export type FriendsAddResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type FriendsAcceptData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}/accept';
};

export type FriendsAcceptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsAcceptError = FriendsAcceptErrors[keyof FriendsAcceptErrors];

export type FriendsAcceptResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FriendsDeclineData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}/decline';
};

export type FriendsDeclineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsDeclineError = FriendsDeclineErrors[keyof FriendsDeclineErrors];

export type FriendsDeclineResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FriendsRemoveData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}';
};

export type FriendsRemoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsRemoveError = FriendsRemoveErrors[keyof FriendsRemoveErrors];

export type FriendsRemoveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
