// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_device_authorization_api_oauth_device_authorization_post
 */
export type BodyDeviceAuthorizationApiOauthDeviceAuthorizationPost = {
    /**
     * Client Id
     */
    client_id?: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Device Uuid
     */
    device_uuid?: string | null;
};

/**
 * Body_device_verify_api_oauth_device_verify_post
 */
export type BodyDeviceVerifyApiOauthDeviceVerifyPost = {
    /**
     * User Code
     */
    user_code?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Approve
     */
    approve?: boolean | null;
};

/**
 * Body_token_api_oauth_token_post
 */
export type BodyTokenApiOauthTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null;
    /**
     * Code Verifier
     */
    code_verifier?: string | null;
    /**
     * Refresh Token
     */
    refresh_token?: string | null;
    /**
     * Device Code
     */
    device_code?: string | null;
};

/**
 * DeviceCodeResponse
 */
export type DeviceCodeResponse = {
    /**
     * Device Code
     */
    device_code: string;
    /**
     * User Code
     */
    user_code: string;
    /**
     * Verification Uri
     */
    verification_uri: string;
    /**
     * Verification Uri Complete
     */
    verification_uri_complete: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Interval
     */
    interval: number;
    /**
     * Message
     */
    message: string;
};

/**
 * DeviceInfo
 */
export type DeviceInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
};

/**
 * Device
 */
export type DeviceRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    status?: DeviceStatus;
};

/**
 * DeviceStatus
 */
export type DeviceStatus = 'online' | 'offline';

/**
 * DeviceVerificationResponse
 */
export type DeviceVerificationResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Device Id
     */
    device_id?: number | null;
    device?: DeviceInfo | null;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Scope
     */
    scope?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RoutineCreate
 */
export type RoutineCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Routine
 */
export type RoutineRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Tasks
     */
    tasks?: Array<TaskInRoutineRead> | null;
};

/**
 * RoutineTaskAdd
 */
export type RoutineTaskAdd = {
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * RoutineUpdate
 */
export type RoutineUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
};

/**
 * TaskInRoutineRead
 */
export type TaskInRoutineRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Position
     */
    position: number;
};

/**
 * Task
 */
export type TaskRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Id
     */
    id: number;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Icon Name
     */
    icon_name?: string | null;
    /**
     * Sound
     */
    sound?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Refresh Token
     */
    refresh_token?: string | null;
};

/**
 * UserCreate
 * Schema for creating a new user.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPasswordUpdate
 * Schema for updating a user's password.
 */
export type UserPasswordUpdate = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserRead
 * Schema for returning user data.
 */
export type UserRead = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DevicesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/devices/';
};

export type DevicesListErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type DevicesListResponses = {
    /**
     * Response Devices List
     * Successful Response
     */
    200: Array<DeviceRead>;
};

export type DevicesListResponse = DevicesListResponses[keyof DevicesListResponses];

export type DevicesGetData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: number;
    };
    query?: never;
    url: '/api/devices/{device_id}';
};

export type DevicesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DevicesGetError = DevicesGetErrors[keyof DevicesGetErrors];

export type DevicesGetResponses = {
    /**
     * Successful Response
     */
    200: DeviceRead;
};

export type DevicesGetResponse = DevicesGetResponses[keyof DevicesGetResponses];

export type UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersMeErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersMeResponse = UsersMeResponses[keyof UsersMeResponses];

export type UsersChangePasswordData = {
    body: UserPasswordUpdate;
    path?: never;
    query?: never;
    url: '/api/users/change-password';
};

export type UsersChangePasswordErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersChangePasswordError = UsersChangePasswordErrors[keyof UsersChangePasswordErrors];

export type UsersChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersListErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type UsersListResponses = {
    /**
     * Response Users List
     * Successful Response
     */
    200: Array<UserRead>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type TokenApiOauthTokenPostData = {
    body?: BodyTokenApiOauthTokenPost;
    path?: never;
    query?: never;
    url: '/api/oauth/token';
};

export type TokenApiOauthTokenPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TokenApiOauthTokenPostError = TokenApiOauthTokenPostErrors[keyof TokenApiOauthTokenPostErrors];

export type TokenApiOauthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type TokenApiOauthTokenPostResponse = TokenApiOauthTokenPostResponses[keyof TokenApiOauthTokenPostResponses];

export type DeviceAuthorizationApiOauthDeviceAuthorizationPostData = {
    body?: BodyDeviceAuthorizationApiOauthDeviceAuthorizationPost;
    path?: never;
    query?: never;
    url: '/api/oauth/device_authorization';
};

export type DeviceAuthorizationApiOauthDeviceAuthorizationPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeviceAuthorizationApiOauthDeviceAuthorizationPostError = DeviceAuthorizationApiOauthDeviceAuthorizationPostErrors[keyof DeviceAuthorizationApiOauthDeviceAuthorizationPostErrors];

export type DeviceAuthorizationApiOauthDeviceAuthorizationPostResponses = {
    /**
     * Successful Response
     */
    200: DeviceCodeResponse;
};

export type DeviceAuthorizationApiOauthDeviceAuthorizationPostResponse = DeviceAuthorizationApiOauthDeviceAuthorizationPostResponses[keyof DeviceAuthorizationApiOauthDeviceAuthorizationPostResponses];

export type DeviceVerifyApiOauthDeviceVerifyPostData = {
    body?: BodyDeviceVerifyApiOauthDeviceVerifyPost;
    path?: never;
    query?: never;
    url: '/api/oauth/device/verify';
};

export type DeviceVerifyApiOauthDeviceVerifyPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeviceVerifyApiOauthDeviceVerifyPostError = DeviceVerifyApiOauthDeviceVerifyPostErrors[keyof DeviceVerifyApiOauthDeviceVerifyPostErrors];

export type DeviceVerifyApiOauthDeviceVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: DeviceVerificationResponse;
};

export type DeviceVerifyApiOauthDeviceVerifyPostResponse = DeviceVerifyApiOauthDeviceVerifyPostResponses[keyof DeviceVerifyApiOauthDeviceVerifyPostResponses];

export type TasksListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksListResponses = {
    /**
     * Response Tasks List
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type TasksListResponse = TasksListResponses[keyof TasksListResponses];

export type TasksCreateData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksCreateError = TasksCreateErrors[keyof TasksCreateErrors];

export type TasksCreateResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type TasksCreateResponse = TasksCreateResponses[keyof TasksCreateResponses];

export type TasksDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksDeleteError = TasksDeleteErrors[keyof TasksDeleteErrors];

export type TasksDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TasksDeleteResponse = TasksDeleteResponses[keyof TasksDeleteResponses];

export type TasksUpdateData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksUpdateError = TasksUpdateErrors[keyof TasksUpdateErrors];

export type TasksUpdateResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type TasksUpdateResponse = TasksUpdateResponses[keyof TasksUpdateResponses];

export type RoutinesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Tasks
         * Include tasks for each routine
         */
        include_tasks?: boolean;
    };
    url: '/api/routines/';
};

export type RoutinesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesListError = RoutinesListErrors[keyof RoutinesListErrors];

export type RoutinesListResponses = {
    /**
     * Response Routines List
     * Successful Response
     */
    200: Array<RoutineRead>;
};

export type RoutinesListResponse = RoutinesListResponses[keyof RoutinesListResponses];

export type RoutinesCreateData = {
    body: RoutineCreate;
    path?: never;
    query?: never;
    url: '/api/routines/';
};

export type RoutinesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesCreateError = RoutinesCreateErrors[keyof RoutinesCreateErrors];

export type RoutinesCreateResponses = {
    /**
     * Successful Response
     */
    201: RoutineRead;
};

export type RoutinesCreateResponse = RoutinesCreateResponses[keyof RoutinesCreateResponses];

export type RoutinesDeleteData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesDeleteError = RoutinesDeleteErrors[keyof RoutinesDeleteErrors];

export type RoutinesDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RoutinesDeleteResponse = RoutinesDeleteResponses[keyof RoutinesDeleteResponses];

export type RoutinesGetData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesGetError = RoutinesGetErrors[keyof RoutinesGetErrors];

export type RoutinesGetResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesGetResponse = RoutinesGetResponses[keyof RoutinesGetResponses];

export type RoutinesUpdateData = {
    body: RoutineUpdate;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesUpdateError = RoutinesUpdateErrors[keyof RoutinesUpdateErrors];

export type RoutinesUpdateResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesUpdateResponse = RoutinesUpdateResponses[keyof RoutinesUpdateResponses];

export type RoutinesTasksListData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksListError = RoutinesTasksListErrors[keyof RoutinesTasksListErrors];

export type RoutinesTasksListResponses = {
    /**
     * Response Routines Tasks List
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksListResponse = RoutinesTasksListResponses[keyof RoutinesTasksListResponses];

export type RoutinesTasksAddData = {
    body: RoutineTaskAdd;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksAddErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksAddError = RoutinesTasksAddErrors[keyof RoutinesTasksAddErrors];

export type RoutinesTasksAddResponses = {
    /**
     * Response Routines Tasks Add
     * Successful Response
     */
    201: Array<TaskInRoutineRead>;
};

export type RoutinesTasksAddResponse = RoutinesTasksAddResponses[keyof RoutinesTasksAddResponses];

export type RoutinesTasksRemoveData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * Position
         */
        position: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks/{position}';
};

export type RoutinesTasksRemoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksRemoveError = RoutinesTasksRemoveErrors[keyof RoutinesTasksRemoveErrors];

export type RoutinesTasksRemoveResponses = {
    /**
     * Response Routines Tasks Remove
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksRemoveResponse = RoutinesTasksRemoveResponses[keyof RoutinesTasksRemoveResponses];

export type RoutinesStartData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/start';
};

export type RoutinesStartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesStartError = RoutinesStartErrors[keyof RoutinesStartErrors];

export type RoutinesStartResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type RoutinesEndData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/end';
};

export type RoutinesEndErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesEndError = RoutinesEndErrors[keyof RoutinesEndErrors];

export type RoutinesEndResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};
