// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccessLevel
 */
export type AccessLevel = 'owner' | 'start' | 'read';

/**
 * Device
 */
export type DeviceRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    status?: DeviceStatus;
};

/**
 * DeviceStatus
 */
export type DeviceStatus = 'online' | 'offline';

/**
 * FriendAdd
 */
export type FriendAdd = {
    /**
     * Friend Code
     */
    friend_code: string;
};

/**
 * FriendRead
 */
export type FriendRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    status?: FriendshipStatus;
};

/**
 * FriendshipStatus
 */
export type FriendshipStatus = 'pending' | 'accepted';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RoutineCreate
 */
export type RoutineCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Routine
 */
export type RoutineRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    access_level?: AccessLevel;
    start_mode?: StartMode;
    /**
     * Notify Mask
     */
    notify_mask?: number;
    /**
     * Tasks
     */
    tasks?: Array<TaskInRoutineRead> | null;
};

/**
 * RoutineShareCreate
 */
export type RoutineShareCreate = {
    /**
     * User Id
     */
    user_id: number;
    access_level?: AccessLevel;
};

/**
 * RoutineShareRead
 */
export type RoutineShareRead = {
    /**
     * User Id
     */
    user_id: number;
    access_level?: AccessLevel;
    /**
     * Username
     */
    username: string;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
};

/**
 * RoutineShareUpdate
 */
export type RoutineShareUpdate = {
    access_level?: AccessLevel;
};

/**
 * RoutineTaskAdd
 */
export type RoutineTaskAdd = {
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * RoutineUpdate
 */
export type RoutineUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    start_mode?: StartMode;
    /**
     * Notify Mask
     */
    notify_mask?: number | null;
};

/**
 * RuntimeActiveRead
 */
export type RuntimeActiveRead = {
    /**
     * Server Time
     */
    server_time: string;
    runtime: RuntimeStateRead;
    routine?: RuntimeRoutineRead;
};

/**
 * RuntimeActorRead
 */
export type RuntimeActorRead = {
    /**
     * Type
     */
    type: string;
    /**
     * Id
     */
    id: string;
};

/**
 * RuntimeCommandAccepted
 */
export type RuntimeCommandAccepted = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Accepted
     */
    accepted?: boolean;
    /**
     * Server Time
     */
    server_time: string;
    sync: RuntimeSyncRead;
    active?: RuntimeActiveRead;
};

/**
 * RuntimeCommandRequest
 */
export type RuntimeCommandRequest = {
    /**
     * Command Id
     */
    command_id: string;
    type: RuntimeCommandType;
    /**
     * Routine Id
     */
    routine_id?: number | null;
    /**
     * Requested At
     */
    requested_at?: string | null;
    /**
     * Source Device Id
     */
    source_device_id?: string | null;
};

/**
 * RuntimeCommandType
 */
export type RuntimeCommandType = 'routine.start' | 'routine.pause' | 'routine.resume' | 'routine.skip' | 'routine.stop' | 'routine.complete';

/**
 * RuntimeEventEnvelope
 */
export type RuntimeEventEnvelope = {
    /**
     * Event Id
     */
    event_id: string;
    event_type: RuntimeEventType;
    /**
     * Server Time
     */
    server_time: string;
    actor?: RuntimeActorRead;
    sync?: RuntimeSyncRead;
    active?: RuntimeActiveRead;
};

/**
 * RuntimeEventType
 */
export type RuntimeEventType = 'runtime.started' | 'runtime.paused' | 'runtime.resumed' | 'runtime.skipped' | 'runtime.stopped' | 'runtime.completed';

/**
 * RuntimeRoutineRead
 */
export type RuntimeRoutineRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Tasks
     */
    tasks: Array<TaskInRoutineRead>;
};

/**
 * RuntimeStateRead
 */
export type RuntimeStateRead = {
    status: RuntimeStatus;
    /**
     * Routine Id
     */
    routine_id?: number | null;
    /**
     * Participant User Ids
     */
    participant_user_ids?: Array<number>;
    /**
     * Current Task Id
     */
    current_task_id?: number | null;
    /**
     * Current Task Position
     */
    current_task_position?: number | null;
    /**
     * Task Started At
     */
    task_started_at?: string | null;
    /**
     * Routine Started At
     */
    routine_started_at?: string | null;
    /**
     * Paused At
     */
    paused_at?: string | null;
    /**
     * Pause Duration
     */
    pause_duration?: number;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * RuntimeStatus
 */
export type RuntimeStatus = 'idle' | 'running' | 'paused' | 'finished';

/**
 * RuntimeSyncRead
 */
export type RuntimeSyncRead = {
    /**
     * Server Time
     */
    server_time: string;
    runtime: RuntimeStateRead;
};

/**
 * StartMode
 */
export type StartMode = 'none' | 'follow_owner' | 'follow_any';

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
};

/**
 * TaskInRoutineRead
 */
export type TaskInRoutineRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Position
     */
    position: number;
};

/**
 * Task
 */
export type TaskRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Icon Name
     */
    icon_name: string;
    /**
     * Sound
     */
    sound: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Id
     */
    id: number;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Icon Name
     */
    icon_name?: string | null;
    /**
     * Sound
     */
    sound?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
};

/**
 * UserRead
 * Schema for returning user data.
 */
export type UserRead = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Oidc Sub
     */
    oidc_sub: string;
    /**
     * Friend Code
     */
    friend_code?: string | null;
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
    /**
     * Id
     */
    id: number;
};

/**
 * UserUpdate
 * Schema for updating a user.
 */
export type UserUpdate = {
    /**
     * Profile Picture
     */
    profile_picture?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DevicesListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/devices/';
};

export type DevicesListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DevicesListError = DevicesListErrors[keyof DevicesListErrors];

export type DevicesListResponses = {
    /**
     * Response Devices List
     * Successful Response
     */
    200: Array<DeviceRead>;
};

export type DevicesListResponse = DevicesListResponses[keyof DevicesListResponses];

export type DevicesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Device Id
         */
        device_id: number;
    };
    query?: never;
    url: '/api/devices/{device_id}';
};

export type DevicesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DevicesGetError = DevicesGetErrors[keyof DevicesGetErrors];

export type DevicesGetResponses = {
    /**
     * Successful Response
     */
    200: DeviceRead;
};

export type DevicesGetResponse = DevicesGetResponses[keyof DevicesGetResponses];

export type UsersMeData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersMeErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersMeError = UsersMeErrors[keyof UsersMeErrors];

export type UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersMeResponse = UsersMeResponses[keyof UsersMeResponses];

export type UsersUpdateMeData = {
    body: UserUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersUpdateMeErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateMeError = UsersUpdateMeErrors[keyof UsersUpdateMeErrors];

export type UsersUpdateMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUpdateMeResponse = UsersUpdateMeResponses[keyof UsersUpdateMeResponses];

export type UsersListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersListError = UsersListErrors[keyof UsersListErrors];

export type UsersListResponses = {
    /**
     * Response Users List
     * Successful Response
     */
    200: Array<UserRead>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type TasksListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksListError = TasksListErrors[keyof TasksListErrors];

export type TasksListResponses = {
    /**
     * Response Tasks List
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type TasksListResponse = TasksListResponses[keyof TasksListResponses];

export type TasksCreateData = {
    body: TaskCreate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksCreateError = TasksCreateErrors[keyof TasksCreateErrors];

export type TasksCreateResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type TasksCreateResponse = TasksCreateResponses[keyof TasksCreateResponses];

export type TasksDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksDeleteError = TasksDeleteErrors[keyof TasksDeleteErrors];

export type TasksDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TasksDeleteResponse = TasksDeleteResponses[keyof TasksDeleteResponses];

export type TasksUpdateData = {
    body: TaskUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type TasksUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TasksUpdateError = TasksUpdateErrors[keyof TasksUpdateErrors];

export type TasksUpdateResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type TasksUpdateResponse = TasksUpdateResponses[keyof TasksUpdateResponses];

export type RoutinesListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Tasks
         * Include tasks for each routine
         */
        include_tasks?: boolean;
    };
    url: '/api/routines/';
};

export type RoutinesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesListError = RoutinesListErrors[keyof RoutinesListErrors];

export type RoutinesListResponses = {
    /**
     * Response Routines List
     * Successful Response
     */
    200: Array<RoutineRead>;
};

export type RoutinesListResponse = RoutinesListResponses[keyof RoutinesListResponses];

export type RoutinesCreateData = {
    body: RoutineCreate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/routines/';
};

export type RoutinesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesCreateError = RoutinesCreateErrors[keyof RoutinesCreateErrors];

export type RoutinesCreateResponses = {
    /**
     * Successful Response
     */
    201: RoutineRead;
};

export type RoutinesCreateResponse = RoutinesCreateResponses[keyof RoutinesCreateResponses];

export type RoutinesDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesDeleteError = RoutinesDeleteErrors[keyof RoutinesDeleteErrors];

export type RoutinesDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RoutinesDeleteResponse = RoutinesDeleteResponses[keyof RoutinesDeleteResponses];

export type RoutinesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesGetError = RoutinesGetErrors[keyof RoutinesGetErrors];

export type RoutinesGetResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesGetResponse = RoutinesGetResponses[keyof RoutinesGetResponses];

export type RoutinesUpdateData = {
    body: RoutineUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}';
};

export type RoutinesUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesUpdateError = RoutinesUpdateErrors[keyof RoutinesUpdateErrors];

export type RoutinesUpdateResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type RoutinesUpdateResponse = RoutinesUpdateResponses[keyof RoutinesUpdateResponses];

export type RoutinesTasksListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksListError = RoutinesTasksListErrors[keyof RoutinesTasksListErrors];

export type RoutinesTasksListResponses = {
    /**
     * Response Routines Tasks List
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksListResponse = RoutinesTasksListResponses[keyof RoutinesTasksListResponses];

export type RoutinesTasksAddData = {
    body: RoutineTaskAdd;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks';
};

export type RoutinesTasksAddErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksAddError = RoutinesTasksAddErrors[keyof RoutinesTasksAddErrors];

export type RoutinesTasksAddResponses = {
    /**
     * Response Routines Tasks Add
     * Successful Response
     */
    201: Array<TaskInRoutineRead>;
};

export type RoutinesTasksAddResponse = RoutinesTasksAddResponses[keyof RoutinesTasksAddResponses];

export type RoutinesTasksRemoveData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * Position
         */
        position: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/tasks/{position}';
};

export type RoutinesTasksRemoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesTasksRemoveError = RoutinesTasksRemoveErrors[keyof RoutinesTasksRemoveErrors];

export type RoutinesTasksRemoveResponses = {
    /**
     * Response Routines Tasks Remove
     * Successful Response
     */
    200: Array<TaskInRoutineRead>;
};

export type RoutinesTasksRemoveResponse = RoutinesTasksRemoveResponses[keyof RoutinesTasksRemoveResponses];

export type RoutinesSharesListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/shares';
};

export type RoutinesSharesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesSharesListError = RoutinesSharesListErrors[keyof RoutinesSharesListErrors];

export type RoutinesSharesListResponses = {
    /**
     * Response Routines Shares List
     * Successful Response
     */
    200: Array<RoutineShareRead>;
};

export type RoutinesSharesListResponse = RoutinesSharesListResponses[keyof RoutinesSharesListResponses];

export type RoutinesSharesCreateData = {
    body: RoutineShareCreate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/shares';
};

export type RoutinesSharesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesSharesCreateError = RoutinesSharesCreateErrors[keyof RoutinesSharesCreateErrors];

export type RoutinesSharesCreateResponses = {
    /**
     * Successful Response
     */
    201: RoutineShareRead;
};

export type RoutinesSharesCreateResponse = RoutinesSharesCreateResponses[keyof RoutinesSharesCreateResponses];

export type RoutinesSharesDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/shares/{user_id}';
};

export type RoutinesSharesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesSharesDeleteError = RoutinesSharesDeleteErrors[keyof RoutinesSharesDeleteErrors];

export type RoutinesSharesDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RoutinesSharesDeleteResponse = RoutinesSharesDeleteResponses[keyof RoutinesSharesDeleteResponses];

export type RoutinesSharesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/shares/{user_id}';
};

export type RoutinesSharesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesSharesGetError = RoutinesSharesGetErrors[keyof RoutinesSharesGetErrors];

export type RoutinesSharesGetResponses = {
    /**
     * Successful Response
     */
    200: RoutineShareRead;
};

export type RoutinesSharesGetResponse = RoutinesSharesGetResponses[keyof RoutinesSharesGetResponses];

export type RoutinesSharesUpdateData = {
    body: RoutineShareUpdate;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/routines/{routine_id}/shares/{user_id}';
};

export type RoutinesSharesUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoutinesSharesUpdateError = RoutinesSharesUpdateErrors[keyof RoutinesSharesUpdateErrors];

export type RoutinesSharesUpdateResponses = {
    /**
     * Successful Response
     */
    200: RoutineShareRead;
};

export type RoutinesSharesUpdateResponse = RoutinesSharesUpdateResponses[keyof RoutinesSharesUpdateResponses];

export type RuntimeActiveData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/active';
};

export type RuntimeActiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeActiveError = RuntimeActiveErrors[keyof RuntimeActiveErrors];

export type RuntimeActiveResponses = {
    /**
     * Successful Response
     */
    200: RuntimeActiveRead;
};

export type RuntimeActiveResponse = RuntimeActiveResponses[keyof RuntimeActiveResponses];

export type RuntimeSyncData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/sync';
};

export type RuntimeSyncErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeSyncError = RuntimeSyncErrors[keyof RuntimeSyncErrors];

export type RuntimeSyncResponses = {
    /**
     * Successful Response
     */
    200: RuntimeSyncRead;
};

export type RuntimeSyncResponse = RuntimeSyncResponses[keyof RuntimeSyncResponses];

export type RuntimeStartData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/start';
};

export type RuntimeStartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeStartError = RuntimeStartErrors[keyof RuntimeStartErrors];

export type RuntimeStartResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimeStartResponse = RuntimeStartResponses[keyof RuntimeStartResponses];

export type RuntimePauseData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/pause';
};

export type RuntimePauseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimePauseError = RuntimePauseErrors[keyof RuntimePauseErrors];

export type RuntimePauseResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimePauseResponse = RuntimePauseResponses[keyof RuntimePauseResponses];

export type RuntimeResumeData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/resume';
};

export type RuntimeResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeResumeError = RuntimeResumeErrors[keyof RuntimeResumeErrors];

export type RuntimeResumeResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimeResumeResponse = RuntimeResumeResponses[keyof RuntimeResumeResponses];

export type RuntimeSkipData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/skip';
};

export type RuntimeSkipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeSkipError = RuntimeSkipErrors[keyof RuntimeSkipErrors];

export type RuntimeSkipResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimeSkipResponse = RuntimeSkipResponses[keyof RuntimeSkipResponses];

export type RuntimeStopData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/stop';
};

export type RuntimeStopErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeStopError = RuntimeStopErrors[keyof RuntimeStopErrors];

export type RuntimeStopResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimeStopResponse = RuntimeStopResponses[keyof RuntimeStopResponses];

export type RuntimeCompleteData = {
    body: RuntimeCommandRequest;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/complete';
};

export type RuntimeCompleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeCompleteError = RuntimeCompleteErrors[keyof RuntimeCompleteErrors];

export type RuntimeCompleteResponses = {
    /**
     * Successful Response
     */
    200: RuntimeCommandAccepted;
};

export type RuntimeCompleteResponse = RuntimeCompleteResponses[keyof RuntimeCompleteResponses];

export type RuntimeEventsData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/runtime/events';
};

export type RuntimeEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeEventsError = RuntimeEventsErrors[keyof RuntimeEventsErrors];

export type RuntimeEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FriendsListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/';
};

export type FriendsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsListError = FriendsListErrors[keyof FriendsListErrors];

export type FriendsListResponses = {
    /**
     * Response Friends List
     * Successful Response
     */
    200: Array<FriendRead>;
};

export type FriendsListResponse = FriendsListResponses[keyof FriendsListResponses];

export type FriendsRequestsListData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/requests';
};

export type FriendsRequestsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsRequestsListError = FriendsRequestsListErrors[keyof FriendsRequestsListErrors];

export type FriendsRequestsListResponses = {
    /**
     * Response Friends Requests List
     * Successful Response
     */
    200: Array<FriendRead>;
};

export type FriendsRequestsListResponse = FriendsRequestsListResponses[keyof FriendsRequestsListResponses];

export type FriendsAddData = {
    body: FriendAdd;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/friends/add';
};

export type FriendsAddErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsAddError = FriendsAddErrors[keyof FriendsAddErrors];

export type FriendsAddResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type FriendsAcceptData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}/accept';
};

export type FriendsAcceptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsAcceptError = FriendsAcceptErrors[keyof FriendsAcceptErrors];

export type FriendsAcceptResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FriendsDeclineData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}/decline';
};

export type FriendsDeclineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsDeclineError = FriendsDeclineErrors[keyof FriendsDeclineErrors];

export type FriendsDeclineResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FriendsRemoveData = {
    body?: never;
    headers?: {
        /**
         * X-Id-Token
         */
        'X-ID-Token'?: string | null;
    };
    path: {
        /**
         * Friend Id
         */
        friend_id: number;
    };
    query?: never;
    url: '/api/friends/{friend_id}';
};

export type FriendsRemoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FriendsRemoveError = FriendsRemoveErrors[keyof FriendsRemoveErrors];

export type FriendsRemoveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
