"""empty message

Revision ID: 342b38619e35
Revises: 7293259d56ba
Create Date: 2026-03-07 23:47:08.841417

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '342b38619e35'
down_revision = '7293259d56ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_runtime_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_routine_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PAUSED', name='runtimestatus'), nullable=False),
    sa.Column('current_task_position', sa.Integer(), nullable=True),
    sa.Column('task_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_runtime_states_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_active_routine_id_routines'), type_='foreignkey')
        batch_op.drop_column('active_routine_id')
        batch_op.drop_column('active_routine_started_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_routine_started_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('active_routine_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_active_routine_id_routines'), 'routines', ['active_routine_id'], ['id'])

    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_runtime_states_user_id'))

    op.drop_table('routine_runtime_states')
    # ### end Alembic commands ###