"""oauthconsent

Revision ID: 3a747f956841
Revises: d253a8b75c21
Create Date: 2026-02-21 23:27:22.945779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3a747f956841'
down_revision = 'd253a8b75c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_consents')
    # ### end Alembic commands ###