"""add active routine

Revision ID: 7293259d56ba
Revises: d1c273a95b44
Create Date: 2026-03-07 20:18:35.833622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7293259d56ba'
down_revision = 'd1c273a95b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_routine_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active_routine_started_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_users_active_routine_id_routines',
            'routines',
            ['active_routine_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_active_routine_id_routines', type_='foreignkey')
        batch_op.drop_column('active_routine_started_at')
        batch_op.drop_column('active_routine_id')

    # ### end Alembic commands ###