"""routine_deletion_cascade

Revision ID: a53584d08a40
Revises: 6b2b1c7c9f41
Create Date: 2026-03-27 22:16:46.921261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a53584d08a40'
down_revision = '6b2b1c7c9f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###