"""shared_runtime_state

Revision ID: b3371fdac6bc
Revises: b48fa28e7279
Create Date: 2026-03-21 18:28:23.639673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b3371fdac6bc'
down_revision = 'b48fa28e7279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ids', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_routine_runtime_states_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_routine_runtime_states_user_id'), ['user_id'], unique=1)
        batch_op.drop_column('user_ids')

    # ### end Alembic commands ###