"""Add start_mode and notify_mask to routine_access

Revision ID: b48fa28e7279
Revises: f01de085e26f
Create Date: 2026-03-21 15:49:29.589570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b48fa28e7279'
down_revision = 'f01de085e26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_mode', sa.Enum('NONE', 'FOLLOW_OWNER', 'FOLLOW_ANY', name='startmode'), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('notify_mask', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_access', schema=None) as batch_op:
        batch_op.drop_column('notify_mask')
        batch_op.drop_column('start_mode')

    # ### end Alembic commands ###