"""routine_runtime_state_participants

Revision ID: e4d4558dd6e8
Revises: b3371fdac6bc
Create Date: 2026-03-21 18:45:38.039251

"""
import json
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e4d4558dd6e8'
down_revision = 'b3371fdac6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_runtime_state_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('runtime_state_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['runtime_state_id'], ['routine_runtime_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_runtime_state_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_runtime_state_participants_runtime_state_id'), ['runtime_state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_runtime_state_participants_user_id'), ['user_id'], unique=True)

    # Migrate data from routine_runtime_states.user_ids to routine_runtime_state_participants
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id, user_ids FROM routine_runtime_states")).fetchall()
    now = datetime.utcnow()
    for row in results:
        rid, user_ids_json = row
        if user_ids_json:
            try:
                if isinstance(user_ids_json, str):
                    user_ids = json.loads(user_ids_json)
                else:
                    user_ids = user_ids_json
                
                if isinstance(user_ids, list):
                    for uid in user_ids:
                        connection.execute(
                            sa.text("INSERT INTO routine_runtime_state_participants (runtime_state_id, user_id, created_at, updated_at) VALUES (:rid, :uid, :now, :now)"),
                            {"rid": rid, "uid": uid, "now": now}
                        )
            except Exception as e:
                print(f"Error migrating users for runtime {rid}: {e}")

    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.drop_column('user_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_runtime_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ids', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('routine_runtime_state_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_runtime_state_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_routine_runtime_state_participants_runtime_state_id'))

    op.drop_table('routine_runtime_state_participants')
    # ### end Alembic commands ###