"""Add friendship status

Revision ID: f01de085e26f
Revises: e8c1c3539c16
Create Date: 2026-03-20 23:31:41.479515

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f01de085e26f'
down_revision = 'e8c1c3539c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendshipstatus'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###